name: Build, Tests, and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    uses: ./.github/workflows/build.yml
  unit-tests:
    needs: build
    uses: ./.github/workflows/vitest.yml
  end-to-end-tests:
    needs: build
    uses: ./.github/workflows/playwright.yml
  deploy:
    needs: [build, unit-tests, end-to-end-tests]
    uses: ./.github/workflows/deploy.yml