name: Run Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (not needed but can be useful if I used a running app instead of a file to test against)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.20.2"
      - run: npm install -g pnpm@8
      - name: Get current date
        id: date
        run: echo "date=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Create pnpm store directory
        run: mkdir -p ~/.pnpm-store
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Cache Playwright dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Install Playwright browsers
        run: pnpm test:pw:ci
      - name: Run Playwright tests
        run: pnpm test:pw:run:project ${{ matrix.browser }}
        env:
          BROWSER_NAME: ${{ matrix.browser }}
          TIMESTAMP: ${{ format(steps.date.outputs.date, 'yyyyMMdd-HHmmss') }}
      - uses: actions/upload-artifact@v3
        env:
          BROWSER_NAME: ${{ matrix.browser }}
          TIMESTAMP: ${{ format(steps.date.outputs.date, 'yyyyMMdd-HHmmss') }}
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ env.BROWSER_NAME }}-${{ env.TIMESTAMP }}
          path: playwright-report/
          retention-days: 30
