name: Run Playwright Tests

on: 
  push:
    branches:
      - master
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.20.2' 
      - run: npm install -g pnpm@8
      - name: Cache dependencies 
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store 
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Prepare Playwright
        run: pnpm test:pw:prepare
      - name: Run Playwright tests
        run: pnpm test:pw:run --browser ${{ matrix.browser }}